name: shopping_cart_with_provider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  badges: ^3.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/apple.jpg
    - assets/banana.jpg
    - assets/cherry.jpg
    - assets/mango.jpg
    - assets/orange.jpg
    - assets/peach.jpg
    - assets/grape.jpg
    - assets/emptycart.jpg

